# Generated by Django 5.2 on 2025-04-23 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_alter_producto_tipoprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipoprod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipoprod'),
        ),
    ]
